### ISSUE TITLE
Some questions about webhook.cool.

### ISSUE THREAD

**Issue by code-changme** [Jaarson/jarekceborski.com#3]
I'm very sorry to bother you, but I have a question that I need your response to: When I send data requests to webhook.cool, are those requests logged on the server or in the logs? For example, are failed 403 requests also logged? Could you please respond? I really need this answer. Thanks.

**Comment by Jaarson** [comment]
Why do you need this answer? What difference does it make?

**Comment by code-changme** [comment]
The situation is this: when I use your webhook.cool service, I send requests with real customer data. In this case, I’d like to know if your server retains this information.

**Comment by Jaarson** [comment]
Every request is logged internally as below (so without payload)

```
2024-09-23 11:37:25.687 | [xxx-yyy-123.webhook.cool] [ip-address] - "POST / HTTP/2.0" status: "200" request_time: "0.025" referer: "-" connection_requests: "1" pipe: "." bytes: "0" request_length: "748" agent: "Automation for Jira AC app/1.0;..."
```

Then, all successful requests are stored in the database, and you can see them in the UI, with the possibility to delete. After you delete them, there is no trace left whatsoever.

There are no requests stored in the database that you couldn't see in the UI.

**Comment by code-changme** [comment]
1. Thank you for the information. Could you please clarify whether the request content is logged in the database when the status is 403?
2. Additionally, are all request payloads also recorded in the server's log files, even if they are not stored in the database?
3. In the webhook.cool UI, if I do not manually delete the data but simply refresh the page, will the data also be deleted?

I look forward to your reply. Thank you!

**Comment by Jaarson** [comment]
1. Request content is not logged on status 403.
2. No payloads are recorded in server logs.
3. Data from the database is only deleted after 7 days since the last request (all requests for this webhook URL are deleted), or when you click "Delete this webhook" from the "..." menu (all requests for this webhook URL are deleted), or when you delete individual requests by clicking on the trash icon next to the request.
